Django_project_3/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from polls import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^_nested_admin/', include('nested_admin.urls')),
]

polls/urls.py
from django.urls import path, re_path, include

from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.QuestionView.as_view(), name='question'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:poll_id>/vote/', views.vote, name='vote'),
    path('logged_out/', LogoutView.as_view(), name='logged_out'),
    path('login/', LoginView.as_view(), name='login'),
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User


class Poll(models.Model):
    poll_text = models.CharField('Название опроса', max_length=200)
    pub_date = models.DateTimeField('Дата публикации')
    is_pub = models.BooleanField('Опубликован', default=True)
    def __str__(self):
        return self.poll_text

    class Meta:
        verbose_name = 'Опрос'
        verbose_name_plural = 'Опросы'


class Question(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    question_text = models.CharField('Вопрос', max_length=200)
    position = models.PositiveSmallIntegerField('Порядок', null=True)

    def __str__(self):
        return self.question_text

    class Meta:
        ordering = ['position']
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField('Ответ', max_length=200)
    position = models.PositiveSmallIntegerField('Порядок', null=True)

    def __str__(self):
        return self.choice_text

    class Meta:
        ordering = ['position']
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'


class UserChoice(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    vote_date = models.DateTimeField('Дата')

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

polls/forms.py
from django import forms

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.utils import timezone
from collections import OrderedDict
from .models import Poll, Question, Choice, UserChoice, User


class IndexView(generic.ListView):
    """Главная страница"""
    template_name = 'polls/index.html'
    context_object_name = 'poll_list'
    queryset = Poll.objects.filter(is_pub=True).order_by('-pub_date')


@method_decorator(login_required(login_url='polls:login'), name='dispatch')
class QuestionView(generic.TemplateView):
    """Страница опроса"""
    model = Question
    template_name = 'polls/question.html'

    def dispatch(self, request, *args, **kwargs):
        poll_is_not_pub = Poll.objects.filter(is_pub=False, id=get_pk(self)).exists()
        user_is_staff = User.objects.filter(username=request.user.username,
                                                is_staff=True).exists()
        user_answered = UserChoice.objects.filter(user__username=request.user.username,
                                                 poll_id=get_pk(self),
                                                 ).exists()
        if poll_is_not_pub:
            """Если опрос не опубликован, не даем перейти по его url"""
            return HttpResponseRedirect(reverse('polls:index', ))
        elif user_is_staff:
            """Администраторы только СОЗДАЮТ опросы, запрос логина"""
            return HttpResponseRedirect(reverse('polls:login', ))
        elif user_answered:
            """Если уже проходили опрос, то смотри результаты"""
            return HttpResponseRedirect(reverse('polls:results', args=(get_pk(self),)))
        else:
            """Наконец, можем пройти опрос"""
            return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return make_question_context(get_pk(self), context)


@method_decorator(login_required(login_url='polls:login'), name='dispatch')
class ResultsView(generic.TemplateView):
    """Страница результатов"""
    model = Question
    template_name = 'polls/results.html'

    def dispatch(self, request, *args, **kwargs):
        poll_is_pub = Poll.objects.filter(is_pub=True, id=get_pk(self)).exists()
        user_answered = UserChoice.objects.filter(user__username=request.user.username,
                                                 poll_id=get_pk(self),
                                                 ).exists()
        if poll_is_pub and user_answered:
            """Могут смотреть результаты только ответившие и только опубликованные опросы"""
            return super().dispatch(request, *args, **kwargs)
        else:
            """В противном случае не пускаем"""
            return HttpResponseRedirect(reverse('polls:index', ))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = make_question_context(get_pk(self), context)
        question_dic = context['question_dic']
        choice_dic = context['choice_dic']
        for question in question_dic:
            sum_votes = sum([choice_dic[choice] for choice in question_dic[question]])
            for choice in question_dic[question]:
                """Добавил новый votes в choice. Не знаю, на сколько это хорошо. Но так наиболее удобно."""
                choice.votes = round(choice_dic[choice]*100/sum_votes, 2)
        return context


def get_pk(class_self):
    """Получаем номер опроса (страницы) из аргументов"""
    return class_self.kwargs.get('pk')


def make_dics(poll_id):
    """question_dic = Ordered {question_obj:[choice_obj, choice_bj, ..]} для нужного poll_id
       choice_dic = {choice_obj:sum_votes} для нужного poll_id
    """
    question_dic = OrderedDict()
    choice_dic = {}
    for question in Question.objects.filter(poll_id=poll_id).order_by('position'):
        choices = Choice.objects.filter(question_id=question.id).order_by('position')
        question_dic[question] = choices
        for choice in choices:
            choice_dic[choice] = UserChoice.objects.filter(choice_id=choice.id).count()
    return question_dic, choice_dic


def make_question_context(poll_id, context):
    """Собираем context"""
    context['question_dic'], context['choice_dic'] = make_dics(poll_id)
    context['poll'] = Poll.objects.get(pk=poll_id)
    return context


def vote(request, poll_id):
    questions_in_poll = [str(x['id']) for x in Question.objects.filter(poll_id=poll_id).values('id')]
    if set(questions_in_poll) - set([str(x) for x in request.POST.keys()]) == set():
        """Убеждаемся, что ответили на все вопросы в опросе"""
        for question_id in questions_in_poll:
            choice_id = request.POST[question_id]
            choice = Choice.objects.get(id=choice_id)
            user_choice = UserChoice(user = User.objects.get(username=request.user.username),
                                    poll = Poll.objects.get(id=poll_id),
                                    question = Question.objects.get(id=question_id),
                                    choice = choice,
                                    vote_date = timezone.now()
                                     )
            user_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(poll_id,)))
    else:
        """Если ответили не на все вопросы"""
        context = make_question_context(poll_id, {})
        context['pk'] = poll_id
        context['error_message'] = "Необходимо ответить на все вопросы"
        return render(request, 'polls/question.html', context)

polls/templates/polls/index.html
{% load static %}
<html>
    <head>
        <title>Приложение "Опросы"</title>
        <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
        <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    </head>
    <body>
        <div id="container">
            <div id="header">
                <div id="branding">
                    <h1><a>Приложение "Опросы"</a></h1>
                </div>
            </div>
            <div style="margin-left: 5%">
                {% if poll_list %}
                    <ul>
                    {% for poll in poll_list %}
                        <li><a style="font-size: 14px" href="{% url 'polls:question' poll.id %}">{{ poll.pub_date}}<tab6>{{ poll.poll_text}}</tab6></a></li>
                    {% endfor %}
                    </ul>
                    <div style="margin-top: 50px">
                        <form action="{% url 'polls:login' %}" method="post">
                            {% csrf_token %}
                        <input type="submit" value="Войти" />
                        </form>
                        <form action="{% url 'polls:logged_out' %}" method="post">
                            {% csrf_token %}
                        <input type="submit" value="Выйти" />
                        </form>
                    </div>
                {% else %}
                    <p class="errornote">Нет опубликованных опросов</p>
                {% endif %}
            </div>
        </div>
    </body>
</html>

polls/templates/polls/logout.html
<p>LOGOUT</p>

polls/templates/polls/question.html
{% load static %}
<html>
    <head>
        <title>{{ poll.poll_text }}</title>
        <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
        <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    </head>
    <body>
        <div id="container">
            <div id="header">
                <div id="branding">
                    <h1><a>{{ poll.poll_text }}</a></h1>
                </div>
            </div>
            <div id="content" class="colMS">
            {% if error_message %}<p class="errornote">{{ error_message }}</p>{% endif %}
                <div id="content-main">
                    <div class="app-polls module">
                        <form action="{% url 'polls:vote' pk %}" method="post">
                            {% csrf_token %}
                            {% for question, choices in question_dic.items %}
                                <table style="width: 100%">
                                    <caption>
                                        <a class="section">{{ question.question_text }}</a>
                                    </caption>
                                    {% for choice in choices %}
                                        <tr>
                                            <td width="10px"><input type="radio" value={{ choice.id }} name={{ question.id }}></td>
                                            <td width="100%"><label>{{ choice.choice_text }}</label></td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            {% endfor %}
                        <div style="margin-top: 50px">
                            <input type="submit" value="Голосовать" />
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

polls/templates/polls/results.html
{% load static %}
<html>
    <head>
        <title>{{ poll.poll_text }}</title>
        <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
        <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    </head>
    <body>
        <div id="container">
            <div id="header">
                <div id="branding">
                    <h1><a>{{ poll.poll_text }}</a></h1>
                </div>
            </div>
            <div id="content" class="colMS">
                <h1>Опрос пройден. Вот результаты:</h1>
                <div id="content-main">
                    <div class="app-polls module">
                        {% for question, choices in question_dic.items %}
                            <table style="width: 100%">
                                <caption>
                                    <a class="section">{{ question.question_text }}</a>
                                </caption>
                                {% for choice in choices %}
                                    <tr>
                                        <td width="80%">{{ choice.choice_text }}</td>
                                        <td width="20%">{{ choice.votes }} %</td>
                                    </tr>
                                {% endfor %}
                            </table>
                        {% endfor %}
                    </div>
                </div>
                <a href="{% url 'polls:index' %}">Вернуться к списку вопросов</a>
            </div>
        </div>
    </body>
</html>